### ISSUE TITLE
ListView vs ListBox

### ISSUE THREAD

**Issue by vangundy** [syncfusion/blazor-docs#30]
Since the **ListView** and **ListBox** components are very similar, it would be helpful if guidance was provided on when to use one over the other.  Some documentation that compares and contrasts these two components would be a good idea.

**Comment by ajithr** [comment]
@vangundy  Thanks for your suggestion. @gsumankumar  @PrabhuSarvesan Could you please check and update on this?

**Comment by Satheeskumar-1989** [comment]
Hi @vangundy,

Please find the below differences.


ListBox | ListView
-- | --
Its [form component](https://ej2.syncfusion.com/documentation/list-box/how-to/form-submit/) and it will display a list of items. The selected items will be submitted when placed within the form. | Its layout component and it will display a list of items.
Supports built-in [filtering](https://ej2.syncfusion.com/documentation/api/list-box/#allowfiltering) and reorder option | Filtering and reorder  can be achieved through [sample](https://ej2.syncfusion.com/documentation/listview/how-to/filter-and-search-list-items-using-listview/) level customization.
Supports dual Listbox with drag and drop and toolbar option to move items between them. | Drag and drop not supported.
Doesn’t support virtualization and multi-level list navigation. | Supports virtualization to load a huge amount of data and multi-level list navigation.

Thanks,
Satheeskumar S

**Comment by vangundy** [comment]
Thank you!  The answer is perfect!

-Paul
